services:
  - type: web
    name: ncomputing-backend
    runtime: node
    rootDir: Backend
    buildCommand: npm install && npx prisma generate
    startCommand: node src/server.js
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: PORT
        value: 8080
